<?php

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class ExamSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('exams')->insert([
            [
                'name'=>"Proeve van Bekwaamheid 3",
                'year'=>"2019",
                'exam_states_id' => '1',
                'education_id' => '10',
                'domain_id' => '2',
                'template'=>'{"groups":[{"name":"Documentatie","questions":[{"question":"De kandidaat kan een document overleggen waarin de requirements voor de webhosting genoemd worden.","explanation":"explanation here","requiredMark":"1"},{"question":"De kandidaat kan een document overleggen waarin vermeld staat hoe content beheerd moet worden.","explanation":"explanation here","requiredMark":"1"},{"question":"De kandidaat kan geen handleiding overleggen","explanation":"explanation here","requiredMark":"2"},{"question":"De handleidingkomt niet overeen met de website","explanation":"explanation here","requiredMark":"2"},{"question":"De kandidaat past versiebeheer toe in zijn handleiding","explanation":"explanation here","requiredMark":0},{"question":"De kandidaat heeft contact gegevens voor verdere vragen opgenomen in de handleiding","explanation":"explanation here","requiredMark":"1"},{"question":"De kandidaat heeft opgenomen in de handleiding hoe gebruikers worden beheerd","explanation":"explanation here","requiredMark":"1"},{"question":"De kandidaat neemt de huidige verie van het cms op in de handleiding","explanation":"explanation here","requiredMark":"1"}]},{"name":"Communicatie","questions":[{"question":"De kandidaat presenteert de handleidingen","explanation":"explanation here","requiredMark":"1"},{"question":"De kandidaat is in staat om details over de handleiding toe te lichten","explanation":"explanation here","requiredMark":"1"},{"question":"De kandidaat heeft geen presentatie voorbereid","explanation":"explanation here","requiredMark":"2"},{"question":"De kandidaat overlegt de handout van de presentatie","explanation":"explanation here","requiredMark":0},{"question":"De kandidaat heeft een agenda in zijn presentatie opgenomen","explanation":"explanation here","requiredMark":0}]},{"name":"Evaluatie","questions":[{"question":"De kandidaat kan aangeven hoe zijn eigen werkwijze in de afgelopen opdracht beter kan","explanation":"explanation here","requiredMark":"1"},{"question":"De kandidaat kan samenvatten welke feedback hij/zij heeft gekregen op de opgeleverde website","explanation":"explanation here","requiredMark":"1"},{"question":"De kandidaat vraagt actief feedback van de opdrachtgever over de kwaliteit van de website","explanation":"explanation here","requiredMark":0}]}],"cesuur":{"marks":["g","o","v"],"calculations":[{"name":"goed","calculation":"[o] == 0 && [v] == 9 && [g] >= 2"},{"name":"vold","calculation":"[v] + [g] - [o] - 10 >= 9 && [o] <= 2 && ([v] - [o] < 9 || [g] < 2)"},{"name":"onv","calculation":"[o] == 2 || [v]+[g]-[o] < 9"}]}}'
            ],
            [
                'name'=>"iteratie oplevering",
                'year'=>"2019",
                'exam_states_id' => '3',
                'education_id' => '10',
                'domain_id' => '2',
                'template'=>'{"groups":[{"name":"Documentatie","questions":[{"question":"De kandidaat kan een document overleggen waarin de requirements voor de webhosting genoemd worden.","explanation":"explanation here","requiredMark":"1"},{"question":"De kandidaat kan een document overleggen waarin vermeld staat hoe content beheerd moet worden.","explanation":"explanation here","requiredMark":"1"},{"question":"De kandidaat kan geen handleiding overleggen","explanation":"explanation here","requiredMark":"2"},{"question":"De handleidingkomt niet overeen met de website","explanation":"explanation here","requiredMark":"2"},{"question":"De kandidaat past versiebeheer toe in zijn handleiding","explanation":"explanation here","requiredMark":0},{"question":"De kandidaat heeft contact gegevens voor verdere vragen opgenomen in de handleiding","explanation":"explanation here","requiredMark":"1"},{"question":"De kandidaat heeft opgenomen in de handleiding hoe gebruikers worden beheerd","explanation":"explanation here","requiredMark":"1"},{"question":"De kandidaat neemt de huidige verie van het cms op in de handleiding","explanation":"explanation here","requiredMark":"1"}]},{"name":"Communicatie","questions":[{"question":"De kandidaat presenteert de handleidingen","explanation":"explanation here","requiredMark":"1"},{"question":"De kandidaat is in staat om details over de handleiding toe te lichten","explanation":"explanation here","requiredMark":"1"},{"question":"De kandidaat heeft geen presentatie voorbereid","explanation":"explanation here","requiredMark":"2"},{"question":"De kandidaat overlegt de handout van de presentatie","explanation":"explanation here","requiredMark":0},{"question":"De kandidaat heeft een agenda in zijn presentatie opgenomen","explanation":"explanation here","requiredMark":0}]},{"name":"Evaluatie","questions":[{"question":"De kandidaat kan aangeven hoe zijn eigen werkwijze in de afgelopen opdracht beter kan","explanation":"explanation here","requiredMark":"1"},{"question":"De kandidaat kan samenvatten welke feedback hij/zij heeft gekregen op de opgeleverde website","explanation":"explanation here","requiredMark":"1"},{"question":"De kandidaat vraagt actief feedback van de opdrachtgever over de kwaliteit van de website","explanation":"explanation here","requiredMark":0}]}],"cesuur":{"marks":["g","o","v"],"calculations":[{"name":"goed","calculation":"[o] == 0 && [v] == 9 && [g] >= 2"},{"name":"vold","calculation":"[v] + [g] - [o] - 10 >= 9 && [o] <= 2 && ([v] - [o] < 9 || [g] < 2)"},{"name":"onv","calculation":"[o] == 2 || [v]+[g]-[o] < 9"}]}}'
            ],
            [
                'name'=>"Test examen",
                'year'=>"2019",
                'exam_states_id' => '4',
                'education_id' => '10',
                'domain_id' => '2',
                'template'=>'{"groups":[{"name":"Documentatie","questions":[{"question":"De kandidaat kan een document overleggen waarin de requirements voor de webhosting genoemd worden.","explanation":"explanation here","requiredMark":"1"},{"question":"De kandidaat kan een document overleggen waarin vermeld staat hoe content beheerd moet worden.","explanation":"explanation here","requiredMark":"1"},{"question":"De kandidaat kan geen handleiding overleggen","explanation":"explanation here","requiredMark":"2"},{"question":"De handleidingkomt niet overeen met de website","explanation":"explanation here","requiredMark":"2"},{"question":"De kandidaat past versiebeheer toe in zijn handleiding","explanation":"explanation here","requiredMark":0},{"question":"De kandidaat heeft contact gegevens voor verdere vragen opgenomen in de handleiding","explanation":"explanation here","requiredMark":"1"},{"question":"De kandidaat heeft opgenomen in de handleiding hoe gebruikers worden beheerd","explanation":"explanation here","requiredMark":"1"},{"question":"De kandidaat neemt de huidige verie van het cms op in de handleiding","explanation":"explanation here","requiredMark":"1"}]},{"name":"Communicatie","questions":[{"question":"De kandidaat presenteert de handleidingen","explanation":"explanation here","requiredMark":"1"},{"question":"De kandidaat is in staat om details over de handleiding toe te lichten","explanation":"explanation here","requiredMark":"1"},{"question":"De kandidaat heeft geen presentatie voorbereid","explanation":"explanation here","requiredMark":"2"},{"question":"De kandidaat overlegt de handout van de presentatie","explanation":"explanation here","requiredMark":0},{"question":"De kandidaat heeft een agenda in zijn presentatie opgenomen","explanation":"explanation here","requiredMark":0}]},{"name":"Evaluatie","questions":[{"question":"De kandidaat kan aangeven hoe zijn eigen werkwijze in de afgelopen opdracht beter kan","explanation":"explanation here","requiredMark":"1"},{"question":"De kandidaat kan samenvatten welke feedback hij/zij heeft gekregen op de opgeleverde website","explanation":"explanation here","requiredMark":"1"},{"question":"De kandidaat vraagt actief feedback van de opdrachtgever over de kwaliteit van de website","explanation":"explanation here","requiredMark":0}]}],"cesuur":{"marks":["g","o","v"],"calculations":[{"name":"goed","calculation":"[o] == 0 && [v] == 9 && [g] >= 2"},{"name":"vold","calculation":"[v] + [g] - [o] - 10 >= 9 && [o] <= 2 && ([v] - [o] < 9 || [g] < 2)"},{"name":"onv","calculation":"[o] == 2 || [v]+[g]-[o] < 9"}]}}'
            ]
        ]);
    }
}
